spring.application.name=MyWebsite
spring.config.import=optional:file:.env[.properties]
# spring.jpa.hibernate.ddl-auto=create
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}

logging.level.root=info
server.port=${PORT:8080}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
